### ISSUE TITLE
What is the purpose of random sessionToken in the User entity?

### ISSUE THREAD

**Issue by YogeshUmeshVaity** [DenzelCode/nest-auth#6]
Hi, you have done a great job with this project! I was just going through the code and was wondering what must be the purpose of `sessionToken` in the User entity. Do you mind explaining it a bit? It looks like it is a random string concantenated to the secret while generating the refreshToken and accessToken. What if we don't use it?

**Comment by DenzelCode** [comment]
Thank you very much!

The purpose of the sessionToken is when you are logged in on different devices and you change your password it gives you the option to log out from all your other devices, if you want to sign off from all of the other devices, it changes your session token.

https://github.com/DenzelCode/nest-auth/blob/a5ba5295ca11340febe367fc8013219c8bb0e9e9/src/features/auth/controller/auth.controller.ts#L105

![image](https://user-images.githubusercontent.com/27902328/145661834-2b043ef5-62e7-457c-8a55-b6d8d809c0e6.png)

**Comment by YogeshUmeshVaity** [comment]
@DenzelCode Thank you!

**Comment by DenzelCode** [comment]
@YogeshUmeshVaity You are welcome.
